name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Bazel
        run: |
          if ! which bazelisk; then
            sudo npm install --location=global @bazel/bazelisk
          fi
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: ~/caches/bazel
          key: bazel-${{ runner.os }}
      - name: Run build
        run: bazel --output_user_root ~/caches/bazel build --explain log --verbose_explanations //...
      - name: Print bazel log
        run: cat log
